version: '3.8'

services:
  app:
    image: aeztic/cdc-gen-backend-api:${VERSION}  # Uses the version passed at runtime
    ports:
      - "8081:8080"
    environment:
      - VERSION=${VERSION}
    env_file:
      - .env
